// <auto-generated />
namespace Company_Site.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SomethingWentWorong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomethingWentWorong));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210923411_SomethingWentWorong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
